# Generated by Django 4.2.5 on 2023-09-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_active_user_is_staff_user_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='salary',
            field=models.FloatField(null=True),
        ),
    ]
