# Generated by Django 4.2.5 on 2023-09-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hourly_payment_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='salary',
            field=models.FloatField(default=0),
        ),
    ]
