# Generated by Django 4.2.5 on 2023-10-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_status_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bank_details',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cv',
            field=models.FileField(null=True, upload_to='cv/'),
        ),
    ]
