# Generated by Django 4.2.5 on 2023-10-04 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_bank_details_user_cv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='date_joined',
            new_name='date_of_joined',
        ),
    ]
