# Generated by Django 4.2.5 on 2023-10-04 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_date_joined_user_date_of_joined'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='date_of_joined',
            new_name='date_joined',
        ),
    ]
