# Generated by Django 4.2.5 on 2023-10-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_date_start_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cv',
            field=models.FileField(null=True, upload_to='media/cv/'),
        ),
    ]
