# Generated by Django 4.2.5 on 2023-10-10 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
