# Generated by Django 4.2.5 on 2023-10-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_position_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cv',
            field=models.FileField(max_length=500, null=True, upload_to='media/cv/'),
        ),
    ]
