# Generated by Django 4.2.5 on 2023-10-18 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_trafficsource_client_traffic_source'),
        ('leads', '0002_lead_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='source',
        ),
        migrations.AddField(
            model_name='lead',
            name='traffic_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='clients.trafficsource'),
        ),
    ]
