# Generated by Django 4.2.5 on 2023-10-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='banner',
            field=models.FileField(null=True, upload_to='media/projects/banners/'),
        ),
    ]
