# Generated by Django 4.2.5 on 2023-11-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_agreement_alter_project_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='slug',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
