# Generated by Django 4.2.5 on 2023-10-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0002_expensetype_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='attachment',
            field=models.FileField(null=True, upload_to='media/cash/expenses/attachments/'),
        ),
    ]
