# Generated by Django 4.2.5 on 2023-10-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0003_alter_expense_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='attachment',
            field=models.FileField(max_length=500, null=True, upload_to='media/cash/expenses/attachments/'),
        ),
    ]
