# Generated by Django 4.2.5 on 2023-10-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='attachment',
            field=models.FileField(max_length=500, null=True, upload_to='media/tasks/attachment/'),
        ),
    ]
